# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Client(object):
    def setupUi(self, Client):
        Client.setObjectName("Client")
        Client.resize(549, 399)
        self.verticalLayout = QtWidgets.QVBoxLayout(Client)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Client)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_ip = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.gridLayout.addWidget(self.lineEdit_ip, 0, 1, 1, 1)
        self.pushButton_offline = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_offline.setObjectName("pushButton_offline")
        self.gridLayout.addWidget(self.pushButton_offline, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_port = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.gridLayout.addWidget(self.lineEdit_port, 1, 1, 1, 1)
        self.pushButton_online = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_online.setObjectName("pushButton_online")
        self.gridLayout.addWidget(self.pushButton_online, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Client)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_dest_UID = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_dest_UID.setObjectName("lineEdit_dest_UID")
        self.gridLayout_2.addWidget(self.lineEdit_dest_UID, 0, 1, 1, 2)
        self.pushButton_conn = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_conn.setObjectName("pushButton_conn")
        self.gridLayout_2.addWidget(self.pushButton_conn, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_localPort = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_localPort.setObjectName("lineEdit_localPort")
        self.gridLayout_2.addWidget(self.lineEdit_localPort, 1, 1, 1, 1)
        self.progressBar_status = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar_status.setProperty("value", 24)
        self.progressBar_status.setTextVisible(False)
        self.progressBar_status.setObjectName("progressBar_status")
        self.gridLayout_2.addWidget(self.progressBar_status, 1, 2, 1, 2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Client)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textEdit_rec = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_rec.setReadOnly(True)
        self.textEdit_rec.setObjectName("textEdit_rec")
        self.gridLayout_3.addWidget(self.textEdit_rec, 0, 0, 1, 1)
        self.pushButton_send = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_send.setMinimumSize(QtCore.QSize(75, 81))
        self.pushButton_send.setObjectName("pushButton_send")
        self.gridLayout_3.addWidget(self.pushButton_send, 1, 1, 1, 1)
        self.textEdit_send = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_send.setObjectName("textEdit_send")
        self.gridLayout_3.addWidget(self.textEdit_send, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setMinimumSize(QtCore.QSize(75, 81))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)

        self.retranslateUi(Client)
        QtCore.QMetaObject.connectSlotsByName(Client)

    def retranslateUi(self, Client):
        _translate = QtCore.QCoreApplication.translate
        Client.setWindowTitle(_translate("Client", "P2P Clinet"))
        self.groupBox.setTitle(_translate("Client", "Server Info"))
        self.label.setText(_translate("Client", "Server IP:"))
        self.lineEdit_ip.setText(_translate("Client", "192.168.0.106"))
        self.pushButton_offline.setText(_translate("Client", "Offline"))
        self.label_2.setText(_translate("Client", "Server Port:"))
        self.lineEdit_port.setText(_translate("Client", "1234"))
        self.pushButton_online.setText(_translate("Client", "Online"))
        self.groupBox_2.setTitle(_translate("Client", "P2P Info"))
        self.label_3.setText(_translate("Client", "Dest Clinet UID:"))
        self.pushButton_conn.setText(_translate("Client", "Connect"))
        self.label_4.setText(_translate("Client", "Local Port:"))
        self.groupBox_3.setTitle(_translate("Client", "Data Info"))
        self.pushButton_send.setText(_translate("Client", "Send"))
        self.pushButton.setText(_translate("Client", "Clear"))

